#!/bin/sh

python pr.py
python shooting.py
python ma-st-sen-norfolk.py
python strange.py
python christie.py
python va-st-hd-50.py
python va-st-hd-51.py
python va-st-hd-67-lemunyon.py
python gillespie.py
python valtgov.py
python va-st-hd-3.py
python va-st-hd-12.py
python va-st-hd-8.py
python va-st-hd-58.py
python va-st-hd-13.py
python va-st-hd-42.py
python chaffetz.py
python valadao.py
python paulsen.py
python royce.py
python issa.py
python roskam.py
python knight.py
python walters.py
python mcsally.py
python denham.py
python heller.py
python nv-gov.py
python mi-sen-stabenow.py
python mi-gov-snyder.py
python petesessions.py
python rohrabacher.py
python culberson.py
python yoder.py
python frelinghuysen.py
python jasonlewis.py
python balart.py
python handel.py
python bacon.py
python scotttaylor.py
python flake.py
python davidyoung.py
python blum.py
python hultgren.py
python trott.py
python rodneydavis.py
python marchant.py
python macarthur.py
python woodall.py
python brat.py
python chabot.py
python bishop.py
python love.py
python tx-22-olson.py
python upton.py
python cruz.py
python poe.py
python amash.py
python nunes.py
python lamarsmith.py
python schweikert.py
python ryan.py
python poliquin.py
python pittenger.py
python johncarter.py
python markwalker.py
python bost.py
python hunter.py
python andybarr.py
python buddycarter.py
python desantis.py
python foxx.py
python hatch.py
python ks-2.py
python pa-hd-18.py
python lamalfa.py
python randyweber.py
python walden.py
python trent-franks.py
python mccarthy.py
python farenthold.py
python mchenry.py
python goodlatte.py
python gowdy.py
python corker.py
python tn-gov.py
python ks-4-ron-estes.py
python steveking.py
python hensarling.py
python meadows.py
python womack.py
python johnjduncan.py
python scalise.py
python mullin.py
python barrasso.py
python babin.py
python dougcollins.py
python tx-01-louie-gohmert.py
python wa-st-sen-45.py
python nj-st-sen-7.py
python larryhogan.py
python va-st-hd-67-lemunyon.py
python va-st-hd-51.py
python il-gov-bruce-rauner.py
python az-st-hd-10-clodfelter.py
python az-st-hd-18-norgaard.py
python az-st-hd-28-mcgee.py
python az-st-hd-28-syms.py
python sc-st-hd-99.py
python lepage.py
python az-1.py
python mi-sen-stabenow.py
python scottwalker.py
python ak-st-sen-k-costello.py
python rickscott.py
python ducey.py
python kasich.py
python txgovgregabbott.py
python ia-gov.py
python tx-ag-paxton.py
python sc-gov-henry-mcmaster.py
python pa-st-hd-10.py
python gianforte.py
python brownback.py
python nc-st-hd-67-justin-burr.py
python id-st-hd-33b-zollinger.py
python wy-gov.py
python ga-st-hd-180.py
python roslehtinen.py
python comstock.py
python coffman.py
python reichert.py
python leonardlance.py
python lobiondo.py
python mccaul.py
python az-5.py
python pa-hd-18.py
python jasonlewis.py
python nc-st-hd-03-michael-speciale.py
python nd-st-hd-39-keith-kempenich.py
python nvstsen20.py