#!/bin/sh

python christie.py
python gillespie.py
python strange.py
python valadao.py
python paulsen.py
python royce.py
python issa.py
python roskam.py
python knight.py
python walters.py
python mcsally.py
python denham.py
python heller.py
python petesessions.py
python rohrabacher.py
python culberson.py
python yoder.py
python frelinghuysen.py
python jasonlewis.py
python balart.py
python bacon.py
python scotttaylor.py
python flake.py
python davidyoung.py
python blum.py
python hultgren.py
python trott.py
python brat.py
python cruz.py
python nunes.py
python schweikert.py
python lamarsmith.py
python ryan.py
python bost.py
python buddycarter.py
python hatch.py
python walden.py
python brownback.py
python mccarthy.py
python gowdy.py
python corker.py
